using System;
using System.Collections.Generic;

#nullable disable

namespace Cedric.Model.Phamacore
{
    public partial class Inventory
    {
        public string InvSubgroupcode { get; set; }
        public string InvCode { get; set; }
        public string Description { get; set; }
        public string InvItemcontents { get; set; }
        public string InvStrength { get; set; }
        public string PackageCode { get; set; }
        public string ManufacturerCode { get; set; }
        public string InvCountryorigin { get; set; }
        public string InvUnit { get; set; }
        public int UnitQty { get; set; }
        public double InvInstockqty { get; set; }
        public int InvOpeningqty { get; set; }
        public int InvMinqty { get; set; }
        public int InvMaxqty { get; set; }
        public int InvReorderqty { get; set; }
        public double InvAvgcost { get; set; }
        public double InvLastunitcost { get; set; }
        public bool? Blocked { get; set; }
        public bool? InvPhysicalitem { get; set; }
        public string TaxCode { get; set; }
        public double InvMinprice { get; set; }
        public double InvMaxprice { get; set; }
        public double InvRetailprice { get; set; }
        public double InvCostprice { get; set; }
        public double InvTradeprice { get; set; }
        public double InvSpecialprice { get; set; }
        public bool? InvBrandgeneric { get; set; }
        public bool? DiscountAvailable { get; set; }
        public string InvNotes { get; set; }
        public bool? TransferItem { get; set; }
        public double? InvAvgsellcost { get; set; }
        public bool? Noexpiry { get; set; }
        public string ProvisionCode { get; set; }
        public bool? Deleted { get; set; }
        public string AltCode { get; set; }
        public int? PackQty { get; set; }
        public bool? RetailItem { get; set; }
        public string Manufacturer { get; set; }
        public string LogicalGroup { get; set; }
        public string LocCode { get; set; }
        public double Salesprofit { get; set; }
        public int? OpeningQty { get; set; }
        public int? Isqty { get; set; }
        public double? Iavgcost { get; set; }
        public double? Ilucost { get; set; }
        public double? Iavgsell { get; set; }
        public string Newcode { get; set; }
        public double? InvOldCostprice { get; set; }
        public double? Newavgcost { get; set; }
        public double? InvoiceDiscount { get; set; }
        public double? CashDiscount { get; set; }
        public string ActiveIngredient { get; set; }
        public string Barcode { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public int? W1 { get; set; }
        public int? W2 { get; set; }
        public double? CalcQty { get; set; }
        public double? Valqty { get; set; }
        public double? Reqty { get; set; }
        public bool? Bonusenabled { get; set; }
        public string V1 { get; set; }
        public string V2 { get; set; }
        public string V3 { get; set; }
        public string V4 { get; set; }
        public string V5 { get; set; }
        public string V6 { get; set; }
        public string V7 { get; set; }
        public string V8 { get; set; }
        public string V9 { get; set; }
        public string V10 { get; set; }
        public double? CarryF { get; set; }
        public double? BroughtF { get; set; }
        public bool? Choose { get; set; }
        public string Gp4code { get; set; }
        public bool? Inclusive { get; set; }
        public bool? Kisimax { get; set; }
        public bool? Lockprice { get; set; }
        public double? InvMinprices1 { get; set; }
        public double? InvMinprices2 { get; set; }
        public double? InvMinprices3 { get; set; }
        public double? InvMaxprices1 { get; set; }
        public double? InvMaxprices2 { get; set; }
        public double? InvMaxprices3 { get; set; }
        public double? InvRetailprices1 { get; set; }
        public double? InvRetailprices2 { get; set; }
        public double? InvRetailprices3 { get; set; }
        public double? InvTradeprices1 { get; set; }
        public double? InvTradeprices2 { get; set; }
        public double? InvTradeprices3 { get; set; }
        public double? InvSpecialprices1 { get; set; }
        public double? InvSpecialprices2 { get; set; }
        public double? InvSpecialprices3 { get; set; }
        public bool? Yeszeroprice { get; set; }
        public bool? Contsub { get; set; }
        public bool? Fastmoving { get; set; }
        public bool? Highvalue { get; set; }
        public bool? Rawmaterial { get; set; }
        public bool? Forrefill { get; set; }
        public string MotherinvCode { get; set; }
        public bool? Notforsale { get; set; }
        public int? Maxqty { get; set; }
        public bool? Ismother { get; set; }
        public bool? Iscontainer { get; set; }
        public double? Suppmarkup { get; set; }
        public double? Suppdisc { get; set; }
        public double? Suppmarkupapply { get; set; }
        public double? Suppdiscapply { get; set; }
        public double? InvWsaleprice { get; set; }
        public double? InvWsaleprices1 { get; set; }
        public double? InvWsaleprices2 { get; set; }
        public double? InvWsaleprices3 { get; set; }
        public bool? Glitem { get; set; }
        public string CalcPw { get; set; }
        public double? Spack { get; set; }
        public string SuppCode { get; set; }
        public string SuppCode2 { get; set; }
        public double? Sweight { get; set; }
        public double? Negstock { get; set; }
        public bool? Proditem { get; set; }
        public int? Prodclass { get; set; }
        public double? InvAvgcostclose { get; set; }
        public double? InvLastunitcostclose { get; set; }
        public int? Formcode { get; set; }
        public int? Classcode { get; set; }
        public double? InvMinpricetrade { get; set; }
        public double? InvMinpriceretail { get; set; }
        public double? InvMinpricewsale { get; set; }
        public double? InvMinpricetradeS1 { get; set; }
        public double? InvMinpriceretailS1 { get; set; }
        public double? InvMinpricewsaleS1 { get; set; }
        public double? InvMinpricetradeS2 { get; set; }
        public double? InvMinpriceretailS2 { get; set; }
        public double? InvMinpricewsaleS2 { get; set; }
        public double? InvMinpricetradeS3 { get; set; }
        public double? InvMinpriceretailS3 { get; set; }
        public double? InvMinpricewsaleS3 { get; set; }
        public int? Counter { get; set; }
        public int? Bcode { get; set; }
        public double? CashinvoiceDiscount { get; set; }
        public bool? Lockitemdiscount { get; set; }
        public bool? Forpackalter { get; set; }
        public string PackinvCode { get; set; }
        public string PackinvName { get; set; }
        public bool? Forpackalterused { get; set; }
        public byte[] Cbrow { get; set; }
    }
}
