using System;
using System.Collections.Generic;

#nullable disable

namespace Cedric.Model.Phamacore
{
    public partial class Snv4t
    {
        public int SaleinvNum { get; set; }
        public int Bcode { get; set; }
        public string CusCode { get; set; }
        public string Memberno { get; set; }
        public DateTime SaleinvDate { get; set; }
        public DateTime? PayDue { get; set; }
        public string OrderNum { get; set; }
        public double? TradeDiscount { get; set; }
        public double? SaleinvVat { get; set; }
        public double? SaleinvD { get; set; }
        public double? SaleinvNet { get; set; }
        public short? CcontNum { get; set; }
        public double? SaleinvTotal { get; set; }
        public bool Batched { get; set; }
        public string SaleinvNumber { get; set; }
        public int? TranspCode { get; set; }
        public double? Insure { get; set; }
        public int? WaybillNum { get; set; }
        public double? TranspCharge { get; set; }
        public string Comments { get; set; }
        public string SalesCode { get; set; }
        public string CusRef { get; set; }
        public double ExchRate { get; set; }
        public string Currencycode { get; set; }
        public bool Selected { get; set; }
        public string AnalysisCode { get; set; }
        public string UserName { get; set; }
        public string GlTradeaccount { get; set; }
        public double? TransportVat { get; set; }
        public double? MiscCharges { get; set; }
        public string Period { get; set; }
        public bool ItemselectionDone { get; set; }
        public DateTime? Lastupdate { get; set; }
        public short Printcopy { get; set; }
        public string BranchCode { get; set; }
        public string SaleinvRef { get; set; }
        public double? XrateNet { get; set; }
        public double? XrateBalance { get; set; }
        public bool? Cashsaleinvoice { get; set; }
        public int? Lastlineno { get; set; }
        public bool? Urgent { get; set; }
        public bool? Bposted { get; set; }
        public int? Invoicetype { get; set; }
        public int? Cuspoints { get; set; }
        public int? Redeemed { get; set; }
        public string RemndNumber { get; set; }
        public bool? Forapproval { get; set; }
        public string Authorisedby { get; set; }
        public double? TtlWeight { get; set; }
        public int? Invtrack { get; set; }
        public double? SaleinvExcise { get; set; }
        public string Clcoredoc { get; set; }
        public bool? Clcoreclosed { get; set; }
        public DateTime? Clcoreclosedate { get; set; }
        public int? Clvisit { get; set; }
        public int? Tillno { get; set; }
        public int? Tillsessno { get; set; }
        public int? Sbcode { get; set; }
        public int? Pricingmode { get; set; }
        public DateTime? Printtime { get; set; }
        public DateTime? Savetime { get; set; }
        public DateTime? Updatetime { get; set; }
        public double? Tltsweight { get; set; }
        public int? Smartstatus { get; set; }
        public string Smartreason { get; set; }
        public int? Weborder { get; set; }
        public DateTime? Rfldate { get; set; }
        public bool? Smartinvoice { get; set; }
        public double? Smartbalanceinv { get; set; }
        public string CusRef2 { get; set; }
        public bool? Copayinvoice { get; set; }
        public int? CopayinvNum { get; set; }
        public int? CopayinvBcode { get; set; }
        public string Patdiag { get; set; }
        public double? Cashpaid { get; set; }
        public bool? Doconhold { get; set; }
        public int? Smartid { get; set; }
        public int? Snvupdatenum { get; set; }
        public string InvCode { get; set; }
        public double Quantity { get; set; }
        public string TaxCode { get; set; }
        public double Price { get; set; }
        public string Unit { get; set; }
        public double Totalcost { get; set; }
        public short? DiscountCode { get; set; }
        public double Bonusdiscount { get; set; }
        public DateTime? Expiry { get; set; }
        public string Description { get; set; }
        public string InvStrength { get; set; }
        public double LineDisc { get; set; }
        public double Newtotalcost { get; set; }
        public double Newprice { get; set; }
        public double? OrdQuantity { get; set; }
        public double? Bonus { get; set; }
        public string ManufC { get; set; }
        public int? SoDetNum { get; set; }
        public double? Returned { get; set; }
        public double? Taken { get; set; }
        public string AdultChild { get; set; }
        public double QtyLeft { get; set; }
        public int ModuleCode { get; set; }
        public bool? PreGrn { get; set; }
        public DateTime TransTime { get; set; }
        public double TaxAmt { get; set; }
        public string DeliveryNo { get; set; }
        public double? QtyOrdered { get; set; }
        public string Documentnumber { get; set; }
        public double? Costofsale { get; set; }
        public int? StkNum { get; set; }
        public int? Mylineno { get; set; }
        public string Partwhole { get; set; }
        public double? Packqty { get; set; }
        public double? Pwqty { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public int? W1 { get; set; }
        public int? W2 { get; set; }
        public int? Authorisecode { get; set; }
        public double? Excise { get; set; }
        public int? ProcCode { get; set; }
        public string EmpNum { get; set; }
        public int? PorderinDetNum { get; set; }
        public double? Itemavgcost { get; set; }
        public double? Tsweight { get; set; }
        public int? Inclusive { get; set; }
        public double? Priceincl { get; set; }
        public int? Promoitem { get; set; }
        public int? WebquoDetNum { get; set; }
        public int? DeptCode { get; set; }
        public int? Rmdays { get; set; }
        public int? Rmtype { get; set; }
        public int? IbiDetNum { get; set; }
        public double? Bonpwqty { get; set; }
        public int SaleinvDetNum { get; set; }
        public bool? Copay { get; set; }
        public int? CopayinvDetNum { get; set; }
        public string Copaycuscode { get; set; }
        public string Copayreason { get; set; }
        public int StkStkNum { get; set; }
        public int Stkentryno { get; set; }
        public int StkModuleCode { get; set; }
        public int? DocDetnum { get; set; }
        public int? DocNum { get; set; }
        public DateTime? DocDate { get; set; }
        public string StkInvCode { get; set; }
        public string BatchNum { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string LocCode { get; set; }
        public double QtyOut { get; set; }
        public bool? Posted { get; set; }
        public int? InstkNum { get; set; }
        public int? Instkentryno { get; set; }
        public string StkUsername { get; set; }
        public string Stkpartwhole { get; set; }
        public double? StkPackqty { get; set; }
        public double? StkPwqty { get; set; }
        public int? StkBcode { get; set; }
        public DateTime? Stksavetime { get; set; }
        public int? Stkref { get; set; }
        public string InvGroupcode { get; set; }
        public string GrpDescription { get; set; }
        public string InvSubgroupcode { get; set; }
        public string SbgrpDescription { get; set; }
        public string ManufacturerCode { get; set; }
        public string ManufDescription { get; set; }
        public string Country { get; set; }
        public string StkDescription { get; set; }
        public string InvItemcontents { get; set; }
        public string PackageCode { get; set; }
        public string InvUnit { get; set; }
        public int UnitQty { get; set; }
        public string StkInvStrength { get; set; }
        public double InvAvgcost { get; set; }
        public double InvLastunitcost { get; set; }
        public bool? InvPhysicalitem { get; set; }
        public double InvMinprice { get; set; }
        public double InvMaxprice { get; set; }
        public double InvRetailprice { get; set; }
        public double InvCostprice { get; set; }
        public double InvTradeprice { get; set; }
        public double InvSpecialprice { get; set; }
        public bool? InvBrandgeneric { get; set; }
        public int? PackQty1 { get; set; }
        public string Manufacturer { get; set; }
        public string ActiveIngredient { get; set; }
        public string Barcode { get; set; }
        public bool? Proditem { get; set; }
        public int? Prodclass { get; set; }
        public int Totrecs { get; set; }
        public int? Bcodefrom { get; set; }
        public int? Bcodeto { get; set; }
        public int Docdetnum1 { get; set; }
        public int? Lineimported { get; set; }
        public bool? Noexpiry { get; set; }
        public bool? Blocked { get; set; }
        public bool? Deleted { get; set; }
        public string ProvisionCode { get; set; }
        public string InvNotes { get; set; }
        public double? InvoiceDiscount { get; set; }
        public double? CashDiscount { get; set; }
        public double? CashinvoiceDiscount { get; set; }
        public string StkTaxCode { get; set; }
    }
}
